### ISSUE TITLE
Document polyline.decode

### ISSUE THREAD

**Issue by dcposch** [mapbox/polyline#24]
When using the `polyline6` option from the Mapbox API, you need to decode the resulting polyline using

```
Polyline.decode(str, 6)
```

It would be great to arguments that `encode` and `decode` expect.

**Comment by tmcw** [comment]
I'm not sure what the request is: to default to 6, or to expose an argument, or to document this in a different way on polyline or Mapbox's side?

We shouldn't change the default to 6. Precision=6 is uncommon, only there because a previous version of the Directions API defaulted to it accidentally. Switching the default to 6 would break the majority of polylines in the wild, including Google's and the recommended `polyline` option on the Mapbox Directions API.

**Comment by dcposch** [comment]
NVM, figured it out. I was looking the wrong place.

**Comment by dcposch** [comment]
This is small enough that, if you want, you could just stick it into the README

https://github.com/mapbox/polyline/blob/master/API.md
