### ISSUE TITLE
Warning - produces different result if coords are [x ,y, something]

### ISSUE THREAD

**Issue by rowanwins** [mapbox/polyline#64]
I just ran a conversion using `polyline.fromGeoJSON(feature)` on some data and when I reconverted back to geojson using `polyline.toGeoJSON(mPolyline)` I got some weird results. 

I dug into my source geojson then noticed it had [x, y, elevation] coordinates, so I trimmed to [x, y], and this produced the expected results.

I'd guess these lines are responsible
https://github.com/mapbox/polyline/blob/master/src/polyline.js#L109-L113

Anyway just a word of warning to others, check your inputs :)

**Comment by andrewharvey** [comment]
Yikes. There is also https://github.com/mapbox/polyline/issues/43 which asks for 3d support, but since the resulting polyline encoding needs to know if it's 2d or 3d, I think it should be opt in and the default should be to ignore any extra coordinates, so consider the current behaviour a bug.

If you had a PR I can provide a second set of eyes to review and we can ping Tristen to try and get it merged, but if not that's fine also.

**Comment by rowanwins** [comment]
> I'd guess these lines are responsible
https://github.com/mapbox/polyline/blob/master/src/polyline.js#L109-L113

Actually those lines are incorrect, will need to dig further to work out why...
